# Generated by Django 4.1.4 on 2022-12-20 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Doctor care', 'Doctor care'), ('Nursing care', 'Nursing care'), ('Medical social services', 'Medical social services'), ('Homemaker or basic assistance care', 'Homemaker or basic assistance care')], default='Doctor Care', max_length=35)),
                ('appointment_time', models.CharField(choices=[('8:00am', '8:00am'), ('9:30am', '9:30am'), ('11:00am', '11:00am'), ('1:00pm', '1:00pm'), ('2:30pm', '2:30pm'), ('4:00pm', '4:00pm'), ('6:00pm', '6:00pm')], default='9:30am', max_length=7)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
