# Generated by Django 4.1.4 on 2022-12-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
