# Generated by Django 4.1.4 on 2022-12-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointments_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='date_sent',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='appointments',
            name='email',
            field=models.EmailField(help_text='Enter your email Address', max_length=100, null=True),
        ),
    ]
