# Generated by Django 4.1.4 on 2022-12-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_date_sent_appointments_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-created_at', 'appointment_time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
