# Generated by Django 4.1.4 on 2022-12-24 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointments_options_appointments_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='datex',
            field=models.DateField(default=datetime.date(2022, 12, 24)),
        ),
    ]
