# Generated by Django 4.1.4 on 2022-12-24 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointments_datex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='datex',
            field=models.DateField(default=datetime.datetime(2022, 12, 24, 2, 32, 2, 546098, tzinfo=datetime.timezone.utc)),
        ),
    ]
