# Generated by Django 4.1.4 on 2022-12-24 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointments_datex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='datex',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
