# Generated by Django 4.1.4 on 2022-12-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointments_datex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='datex',
            new_name='date',
        ),
    ]
