# Generated by Django 4.1.4 on 2022-12-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_rename_datex_appointments_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-date', 'appointment_time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='created_at',
        ),
    ]
